language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  global:
    - PYTHONWARNINGS="default,ignore::PendingDeprecationWarning,ignore::ResourceWarning"
  matrix:
    - DB="POSTGRESQL"
    - DB="MYSQL"

sudo: false

cache: pip

services:
  - postgres
  - mysql

before_install:
  - pip install codecov
  - if [[ $DB = "POSTGRESQL" ]]; then pip install -q psycopg2; fi
  - if [[ $DB = "MYSQL" ]]; then pip install -q mysqlclient; fi
  - pip install -e git+https://github.com/modoboa/modoboa.git#egg=modoboa

install:
  - pip install -q -r requirements.txt
  - pip install -q -r test-requirements.txt
  - python setup.py -q develop

before_script:
  - if [[ $DB = "POSTGRESQL" ]]; then psql -c "CREATE DATABASE modoboa_test;" -U postgres; fi
  - if [[ $DB = "MYSQL" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS modoboa_test;" -uroot; fi
  - if [[ $DB = "MYSQL" ]]; then mysql -e "CREATE USER 'modoboa'@'localhost' IDENTIFIED BY 'modoboa'" -uroot; fi
  - if [[ $DB = "MYSQL" ]]; then mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'modoboa'@'localhost';" -uroot; fi

script:
  - cd test_project
  - coverage run --source ../modoboa_pdfcredentials manage.py test modoboa_pdfcredentials

after_success:
  - codecov

before_deploy:
  - cd ../modoboa_pdfcredentials
  - django-admin compilemessages
  - cd ..

deploy:
  provider: pypi
  user: tonio
  password:
    secure: OXLFdbuNjI/P1g+imXCLmskRTEMLvx3LqkT6NDESXKOEU7yxApfugM4LonjrNEC44HjAGtywNlAxHsUjpv4iDoZe7zVpRBVUSANgk8fiW+r0QK56bGlKG7RYIhdgZPycKtbWbmuffuRs+QiPsyqAGvuCMs9MsbFkZDtEmOdf4jw=
  on:
    tags: true
